# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3941a0f21f7c1377b8c3bfbe723602e54127b82155f2e817661666bcae42d2a064b73b01a43e71265295983b5d8b1bef11cb00c36d3862002a18a6406e53f82

test:
  secret_key_base: ea32e40f8e3e448a498d3d57b5e415b3aa37af6cba7d9bd4ea9c39ae25e78196e2ac38e69bcdd05728f2fbe6d08986e9004fdd5fc531ce721beb2bcf127963c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
